stages:
  - deploy

variables:
  GITHUB_REPO: "https://$GITHUB_TOKEN@github.com/dawoldo/Web"
  BACKEND_SRC: "src/backend"
  FRONTEND_SRC: "src/frontend"

before_script:
  - apt-get update -y && apt-get install -y git
  - git config --global user.name "GitLab CI"
  - git config --global user.email "ci@example.com"
  - git remote add github "${GITHUB_REPO}" || echo "GitHub remote exists"
  - git fetch origin

deploy-backend:
  stage: deploy
  script:
    # Create clean branch
    - git checkout --orphan prod-backend
    - git reset --hard
    
    # Get backend files AND its Dockerfile
    - mkdir -p "${BACKEND_SRC}"
    - git checkout origin/main -- "${BACKEND_SRC}/" "dockerfile.backend"
    
    # Rename Dockerfile for Dokku compatibility
    - mv dockerfile.backend Dockerfile
    
    # Commit and push
    - git add .
    - git commit -m "Deploy backend $(date +'%Y-%m-%d %H:%M')"
    - git push github prod-backend --force
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

deploy-frontend:
  stage: deploy
  script:
    # Create clean branch
    - git checkout --orphan prod-frontend
    - git reset --hard
    
    # Get frontend files AND its Dockerfile
    - mkdir -p "public" "${FRONTEND_SRC}"
    - git checkout origin/main -- "public/" "${FRONTEND_SRC}/" "dockerfile.frontend"
    
    # Rename Dockerfile for Dokku compatibility
    - mv dockerfile.frontend Dockerfile
    
    # Commit and push
    - git add .
    - git commit -m "Deploy frontend $(date +'%Y-%m-%d %H:%M')"
    - git push github prod-frontend --force
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual